version: "3.8"
services:
  symbol_service:
    build:
      context: ./symbol_service 
      dockerfile: Dockerfile.sym
    hostname: symbol_service
    command: bundle exec ruby application.rb -p 4567 -s Puma -e production
    ports:
      - "4567:4567"
  backend:
    build:
      context: ./backend 
      dockerfile: Dockerfile.api
    hostname: backend
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: 'true'
      SECRET_KEY_BASE: a52f32929e32451f80a595cbd726eebf8ce49df9cd102834f8c84ced4314dbb8449cea7e22d0e605347abfbe3f3b68f7ac42a430baa69f38312839485e5bc5dd
    command: rails s -p 4000 -b '0.0.0.0'
    ports:
      - "4000:4000"
  web_client:
    build:
      context: ./web_client
      dockerfile: Dockerfile.web
    hostname: web_client
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
      - symbol_service
      - backend
    ports:
      - "3000:80"
