FROM node:14.1.0-alpine as builder

WORKDIR /app
COPY . /app
RUN yarn install --silent

RUN yarn build

FROM nginx:1.19.2-alpine
COPY --from=builder /app/build/ /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf

# COPY nginx/default.conf.template /etc/nginx/conf.d/default.conf.template
COPY nginx/nginx.conf /etc/nginx/conf.d


EXPOSE 80

# COPY ./docker-entrypoint.sh /
# RUN chmod +x /docker-entrypoint.sh

# ENTRYPOINT ["/docker-entrypoint.sh"]

# CMD envsubst $PORT < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'